services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ./plugin/kong-tigre-header:/usr/local/bin/kong-tigre-header
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=bundled,kong-tigre-header
      - KONG_PLUGINSERVER_NAMES=kong-tigre-header
      - KONG_PLUGINSERVER_GO_HEADER_PLUGIN_START_CMD=/usr/local/bin/kong-tigre-header -dump
      - KONG_PLUGINSERVER_GO_HEADER_PLUGIN_QUERY_CMD=/usr/local/bin/kong-tigre-header -dump
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8445 ssl http2
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8446 ssl
      - KONG_ADMIN_GUI_PATH=/manager
      - KONG_ADMIN_GUI_URL=http://localhost:8002/manager
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8445:8445"
    networks:
      - estudo-kong-network

  usuario-api-1:
    build:
      context: ./api-usuario1
      dockerfile: Dockerfile
    container_name: usuario-api-1
    ports:
      - "5001:80"
    networks:
      - estudo-kong-network

  usuario-api-2:
    build:
      context: ./api-usuario2
      dockerfile: Dockerfile
    container_name: usuario-api-2
    ports:
      - "5002:8080"
    networks:
      - estudo-kong-network

  usuario-api-3:
    build:
      context: ./api-usuario3
      dockerfile: Dockerfile
    container_name: usuario-api-3
    ports:
      - "5003:8080"
    networks:
      - estudo-kong-network

networks:
  estudo-kong-network: